### ISSUE TITLE
Having a personnal Luck counter like the Party AP

### ISSUE THREAD

**Issue by Vaslayak** [Muttley/foundryvtt-fallout#101]
Like the Party AP it would be nice to be able to easily add or substract luck point. 
![Capture d’écran 2024-01-10 204538](https://github.com/Muttley/foundryvtt-fallout/assets/109117919/d7ad0ea4-4063-44df-9a4f-58f2b2f94b02)

**Comment by Muttley** [comment]
TBH I don't see this being a necessity as the current luck value is already displayed on the character sheet.  We could maybe add some simple macros for increasing/decreasing this luck value so it doesn't have to be done manually.
