### ISSUE TITLE
Skill translation on NPC sheets

### ISSUE THREAD

**Issue by sanawabicz** [Muttley/foundryvtt-fallout#104]
Skill names based on NPCs sheet are not translated. (Due to "drag and drop" from skill compendium?)

![obraz](https://github.com/Muttley/foundryvtt-fallout/assets/148983564/fe44dffd-9ebf-4f63-a11c-5aaf9ff7c3a0)

Workaround is to create own (translated) skills compendium and use them.

**Comment by Muttley** [comment]
Yes, this is the downside of being able to make custom Skills, and the reason why it's possible in the system settings to specify which Skills compendium to use when a character is first created.
