### ISSUE TITLE
Add macros that the GM can use to adjust player Hunger, Thirst, Sleep levels

### ISSUE THREAD

**Issue by Muttley** [Muttley/foundryvtt-fallout#107]
A simple way for the GM to manage these levels by stepping them up/or down now that recovery is automatic from consuming food/drink items.

**Comment by bb46003** [comment]
`const character = game.actors;
let names = [];
let ahunger = [];
let athirsty = [];
let aspeep = [];
let i = 0;
let actorsid=[];

character.forEach((element) => {
    if (element.type === "character") {
        names[i] = element.name;
        actorsid[i]=element._id;
        ahunger[i] = element.system.conditions.hunger;
        athirsty[i] = element.system.conditions.thirst;
        aspeep[i] = element.system.conditions.sleep;
        i++;
    }
});

names[i+1]=game.i18n.localize("OWNERSHIP.AllPlayers");
let alla=i+1;
let conditionOptionsHunger = [
     game.i18n.localize("FALLOUT.TEMPLATES.conditions.full"),
     game.i18n.localize("FALLOUT.TEMPLATES.conditions.sated"),
    game.i18n.localize("FALLOUT.TEMPLATES.conditions.peckish"),
    game.i18n.localize("FALLOUT.TEMPLATES.conditions.hungry"),
     game.i18n.localize("FALLOUT.TEMPLATES.conditions.starving")
];
let conditionOptionsHydration = [
    game.i18n.localize("FALLOUT.TEMPLATES.conditions.quenched"),
    game.i18n.localize("FALLOUT.TEMPLATES.conditions.hydrated"),
   game.i18n.localize("FALLOUT.TEMPLATES.conditions.thirsty"),
   game.i18n.localize("FALLOUT.TEMPLATES.conditions.dehydrated"),
];
let conditionOptionsSleep = [
    game.i18n.localize("FALLOUT.TEMPLATES.conditions.rested"),
    game.i18n.localize("FALLOUT.TEMPLATES.conditions.tired"),
   game.i18n.localize("FALLOUT.TEMPLATES.conditions.weary"),
   game.i18n.localize("FALLOUT.TEMPLATES.conditions.exhausted"),
];

function generateDynamicTable() {
    let tableBody = ''; // zmiana

    // Generate rows dynamically based on data
    names.forEach(name => {
        let row = document.createElement('tr');

        // Name column
        let nameCell = document.createElement('td');
        nameCell.textContent = name;
        row.appendChild(nameCell);
// Hunger column
i=0;
let hungerCell = document.createElement('td');
conditionOptionsHunger.forEach(option => {
    let radio = document.createElement('input');
    radio.type = 'radio';
    radio.name = `hunger_${name}`; // Unikalna nazwa dla każdego gracza
    let label = document.createElement('label');
    radio.value=i;
    label.textContent = option;
    hungerCell.appendChild(radio);
    hungerCell.appendChild(label);
    hungerCell.appendChild(document.createElement('br'));
    i++
});
row.appendChild(hungerCell);
i=0;
// Hydration column
let hydrationCell = document.createElement('td');
conditionOptionsHydration.forEach(option => {
    let radio = document.createElement('input');
    radio.type = 'radio';
    radio.name = `hydration_${name}`; // Unikalna nazwa dla każdego gracza
    let label = document.createElement('label');
    radio.value=i;
    label.textContent = option;
    hydrationCell.appendChild(radio);
    hydrationCell.appendChild(label);
    hydrationCell.appendChild(document.createElement('br'));
    i++
});
row.appendChild(hydrationCell);
i=0;
// Sleep column
let sleepCell = document.createElement('td');
conditionOptionsSleep.forEach(option => {
    let radio = document.createElement('input');
    radio.type = 'radio';
    radio.name = `sleep_${name}`; // Unikalna nazwa dla każdego gracza
    let label = document.createElement('label');
    radio.value=i;
    label.textContent = option;
    sleepCell.appendChild(radio);
    sleepCell.appendChild(label);
    sleepCell.appendChild(document.createElement('br'));
    i++
});
row.appendChild(sleepCell);

        tableBody += row.outerHTML; // zmiana
    });

    return tableBody; // zmiana
}

// Call the function to generate table
const tableBody = generateDynamicTable(); // zmiana
const actorsn = game.i18n.localize("DOCUMENT.Actors");
const Hunger= game.i18n.localize("FALLOUT.TEMPLATES.conditions.hunger");
const Hydration= game.i18n.localize("FALLOUT.TEMPLATES.conditions.thirst");
const Sleep= game.i18n.localize("FALLOUT.TEMPLATES.conditions.sleep");
const dialog = `
<style>
.window-app {
    overflow: auto;
            
}
        #table-container {
            width: auto
            
        }

        #dynamic-table {
            table-layout: auto;
            width: auto;
        }
        
    </style>
    <body>
<div id="table-container">
    <table id="dynamic-table">
        <thead>
            <tr>
                <th>${actorsn}</th>
                <th>${Hunger}</th>
                <th>${Hydration}</th>
                <th>${Sleep}</th>
            </tr>
        </thead>
        <tbody>
        ${tableBody}
        </tbody>
    </table>
</div>
`;


let d= new Dialog({
    title: "Select a character and their condition",
    content: dialog,
    buttons: {
        select: {
            label: "Select",
            callback: (html) => {
                
            
                names.forEach((name, idnex) => {
                    let selectedHunger = html.find(`input[name="hunger_${name}"]:checked`).val();
                    let selectedHydration = html.find(`input[name="hydration_${name}"]:checked`).val();
                    let selectedSleep = html.find(`input[name="sleep_${name}"]:checked`).val();
                    let aid = actorsid[idnex];
                    console.log(aid)
                    if(aid!=undefined){
                    if(selectedHunger!= null || selectedHydration!=null ||selectedSleep!=null){
                        if(selectedHunger!= null){
                            
                            game.actors.get(aid).update({"system.conditions.hunger": selectedHunger})
                        }
                        if(selectedHydration!= null){
                            
                            game.actors.get(aid).update({"system.conditions.thirst": selectedHydration})
                        }
                        if(selectedSleep!= null){
                            
                            game.actors.get(aid).update({"system.conditions.sleep": selectedSleep})
                        }

                    }
                   
                }
                if(aid===undefined){
                    
                        actorsid.forEach((id)=>{
                            console.log(id)
                        if(selectedHunger!= null || selectedHydration!=null ||selectedSleep!=null){
                            if(selectedHunger!= null){
                                
                                game.actors.get(id).update({"system.conditions.hunger": selectedHunger})
                            }
                            if(selectedHydration!= null){
                                
                                game.actors.get(id).update({"system.conditions.thirst": selectedHydration})
                            }
                            if(selectedSleep!= null){
                                
                                game.actors.get(id).update({"system.conditions.sleep": selectedSleep})
                            }
                        }
    
                        })
                }
            
            
                    
                });
            
               
            }
    },
        cancel: {
            label: "Cancel"
        }
    },
    default: "cancel"
});
let dialogOptions = {
    width: `auto`,
    height: `auto`
};

d.render(true, dialogOptions); `

it do exaclty this ther is need to put proper css

**Comment by Muttley** [comment]
> [Fallout_macro.json](https://github.com/Muttley/foundryvtt-fallout/files/14352570/Fallout_macro.json)
> 
> it do exaclty this ther is need to put proper css

Thanks.  I shall have a look at this in the next few days.

**Comment by Muttley** [comment]
This has been kind of superceded by the game time based automatic adjustment of these values.
