### ISSUE TITLE
Health Bonus Input

### ISSUE THREAD

**Issue by Faraday487** [Muttley/foundryvtt-fallout#133]
It might be handy to have an additional box on the status section of the sheet (beneath Power Armor health, maybe?) to apply health bonuses from perks like Life Giver.  I've caught myself looking all over the sheet and have found nothing to apply a health bonus, unless I've missed something very obvious.

I was able to get this to apply with a system.health.bonus active effect, but it was a little finicky.  Obviously not a huge concern if it's a pain in the ass, since the active effects can handle it.

**Comment by Muttley** [comment]
Active Effects is probably the best way for this, but the finickiness should be helped by #44 when I get to it.
