### ISSUE TITLE
Updating from a previous version causing sheets to not show skills and items

### ISSUE THREAD

**Issue by BlubberNibble** [Muttley/foundryvtt-fallout#134]
I recently updated the system and I noticed that because of this sudden jump in version, some of my player's sheets stopped displaying some data. A large portion of the skills were missing, leaving the sheet with about 8 of the skills in total. It also caused some items in their Weapons inventory to disappear and for a large portion of their perks to disappear as well. This issue also seemed to happen to only some of the player's sheets and not all of them.

After disabling modules to make sure it wasn't an issue there, I noticed that using the Item Piles module would let me see their inventories without opening the sheet itself. When I looked there, I saw that the items that went missing are still in the inventory, they just weren't appearing. This seemed to also happen with new items added in, as trying to add a Railway Rifle and Railway Spikes caused them to vanish when placed in the inventory, but the Item Piles showed it was still in their inventory. Changing the name of the item allowed it to work and display on the sheet, but any time it was named Railway Spike or Railway Rifle, it failed to display on the sheet. Trying to add the skills back in also didn't work, but I believe it's caused by the same issue of their names.

**Comment by Muttley** [comment]
Can you give me specific names of characters that had this issue so I can investigate them using the data you provided the other day?

**Comment by Muttley** [comment]
Closing as the following tickets have been created to resolve this problem: #137 and #138
