### ISSUE TITLE
Character Sheet enhancements

### ISSUE THREAD

**Issue by Unworthypilot** [Muttley/foundryvtt-fallout#136]
can you add some character sheet options that include all the important things on a single tab, like your SPECIAL, HP, Rads, equipped weapons and armor, etc. This would help speed things up for players having it all on one page and make it easier to look at your things at a glance.

**Comment by Muttley** [comment]
While I'm always interested in specific ways to improve accessibility and workflows, making fundamental changes to the character sheet is not really on the priority list at the moment I'm afraid.
