### ISSUE TITLE
Dynamic After Effects is no longer compatible with Fallout 2d20

### ISSUE THREAD

**Issue by BlubberNibble** [Muttley/foundryvtt-fallout#167]
About a month back I've been using DAE in order to more easily implement Effects to update some of the now automatically calculated derived statistics like Life Giver for Max HP, when I noticed that DAE was no longer enabled on that world. I made sure I had the module installed, which I did, only to see it wasn't available among the list of modules for that game.
![image](https://github.com/Muttley/foundryvtt-fallout/assets/115412663/161655c6-4272-4563-ad5b-1ac47f036b49)
![image](https://github.com/Muttley/foundryvtt-fallout/assets/115412663/503502ed-d05c-40db-bf39-b26c5f7a636c)

**Comment by Muttley** [comment]
You'll need to raise this with the developer of the DAE module I'm afraid.
