### ISSUE TITLE
Allow settlement job assignment numbers to be modified by Active Effects

### ISSUE THREAD

**Issue by QckSilverDragon** [Muttley/foundryvtt-fallout#169]
Im playing around with the settlement sheets and found out that each settler has to be a separate NPC sheet.
Can you make it so multiple NPC sheets can be added? I dont need each settler to have unique atributes and having a bunch of Settler (copy) sheets is annoying.

![image](https://github.com/Muttley/foundryvtt-fallout/assets/4044050/734f1c7a-cf8a-4199-97b7-4b1f9816cc81)

**Comment by Muttley** [comment]
I guess it depends on how far into RPing running a settlement your players want to go.  Having actual NPC (and don't forget, settlements will start small and gradually grow) will allow players to form attachments.

Anyway, you can already use an active effect to adjust the amount of people in a settlement with the `system.people.mod` value.

I will also add support for modifying the number of job assignments with the following keys:

```
system.assignments.build
system.assignments.business
system.assignments.guard
system.assignments.hunting_and_gathering
system.assignments.scavenging
system.assignments.tend_crops
system.assignments.trade_caravan
system.assignments.unnasigned
```

**Comment by QckSilverDragon** [comment]
Thanks for the update.

My plan for RP was to just maintain a journal for named NPCs and their backstory. Most of the settlement mechanics dont require the settler to roll anything so just having a list of names and their assignment is beneficial.
If the NPC needs to roll, i have generic NPC sheets i would use. (i.e. wastelander, farmer, merchant) This will make it so blank sheets arent needed just for the NPCs name/assignment to work.
