### ISSUE TITLE
Actor skills being overwritten when the Actor is duplicated

### ISSUE THREAD

**Issue by QckSilverDragon** [Muttley/foundryvtt-fallout#19]
In the picture you can see the skills for the left sheet did not retain the skill info.
I just right clicked the original and clicked Duplicate.
![image](https://github.com/Muttley/foundryvtt-fallout/assets/4044050/2b3382c3-ac28-436d-8fc9-c8ac7ba9cb40)

**Comment by Muttley** [comment]
I can see that here as well.

The duplication is actually done by Foundry itself, so I'm not sure what's going on there.  Possibly a Foundry bug.

**Comment by Muttley** [comment]
Will be fixed in the next release
