### ISSUE TITLE
Give ability to disable automatic XP calculation for people who wish to homebrew the level break points

### ISSUE THREAD

**Issue by Teylah57** [Muttley/foundryvtt-fallout#191]
Actually we can't modify the XP value for level because it's lock

**Comment by Muttley** [comment]
The XP value is calculated using the formula in the core rules so they should be correct.

**Comment by Teylah57** [comment]
it's correct, just I think it's too quickly. So I just wanted to have the possibility to modify it but it's locked. And you tell me on the discord to open a ticket here. But if it's to hard/long to do, it's not a big deal.

**Comment by Muttley** [comment]
> it's correct, just I think it's too quickly. So I just wanted to have the possibility to modify manually but it's locked. And you tell me on the discord to open a ticket here. But if it's to hard/long to do, it's not a big deal.

Ah, OK.  What I can probably do is have a checkbox to disable the auto-calculation for those who want to go with custom XP values and wish to manually enter them.

I'll put this in the queue for a later release.
