### ISSUE TITLE
Apparel Missing Info

### ISSUE THREAD

**Issue by sds2413** [Muttley/foundryvtt-fallout#198]
No individual "Raider Armor" pieces. Ie Leg, Arm, etc.
Apparel that can have the Ballistic Weave mod have max mod set to "0" instead of "1".
All armor are missing the second list of mods they can use in item description. Ie Resin, Padded, Braced, Stabilized, etc
All Power Armor pieces are missing descriptions.* Not sure if you can, I just repeated the main block of text for each piece in a set.

**Comment by Muttley** [comment]
Splitting these out into seperate tickets:

- [ ] #203 
- [ ] #204
- [ ] #205
- [ ] #206
