### ISSUE TITLE
BUG: The quantity text box in gear does not function like other number boxes

### ISSUE THREAD

**Issue by QckSilverDragon** [Muttley/foundryvtt-fallout#20]
In other text boxes you can double-click to select everything and you can click between numbers to place the cursor but in the gear and ammo quantity boxes, you cant.

**Comment by Muttley** [comment]
I'm unable to replicate this.

**Comment by QckSilverDragon** [comment]
I use Firefox to access my server. Here is a recording of me performing the action. 
I first double-click the skill value and it selects the number.
I then goto gear and try to do the same to the number of stimpacks but bl-click doesnt do anything. I then use the arrow key to move the cursor to the right. 
I also attempt to click and drag a selection box on the number and it just tries to move the whole item.

![Click testing](https://github.com/Muttley/foundryvtt-fallout/assets/4044050/96f7e7f6-97c5-4caf-a3d3-adbf6c644c9b)

**Comment by Muttley** [comment]
OK, I can see the issue in Firefox too.  Works fine in Chrome & Brave though.

I think it might be related to the way item dragging is setup, so it's not going to be a quick fix I'm afraid.

**Comment by Muttley** [comment]
This appears to be a browser issue, so there's not a lot I can do with it.
