### ISSUE TITLE
#171 new text parser has some bugs

### ISSUE THREAD

**Issue by QckSilverDragon** [Muttley/foundryvtt-fallout#200]
In regards to update #171 
I was testing out the new text parser for using nCD or nDC and have a few inconsistant results.
I created a new journal entry filled out like this.
![image](https://github.com/Muttley/foundryvtt-fallout/assets/4044050/f061fc26-07fe-41e8-93f7-43e725aec315)

There seem to be some issues with the CD option. When i tried to click the last entry "[[/r 1CD]]" i get this error.
![image](https://github.com/Muttley/foundryvtt-fallout/assets/4044050/c5843b63-3a17-4648-9cfa-b6d673b15f85)

**Comment by Muttley** [comment]
> There seem to be some issues with the CD option. When i tried to click the last entry "[[/r 1CD]]" i get this error.
> ![image](https://private-user-images.githubusercontent.com/4044050/309968222-c5843b63-3a17-4648-9cfa-b6d673b15f85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NTM4MTAsIm5iZiI6MTcwOTY1MzUxMCwicGF0aCI6Ii80MDQ0MDUwLzMwOTk2ODIyMi1jNTg0M2I2My0zYTE3LTQ2NDgtOWNmYS1iNmQ2NzNiMTVmODUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDVUMTU0NTEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWYwNTgzYWE1ODA4MTI4YjIyYjY2ZjFkNzc5MTVkYjE1M2JhZTIxMTVjYWEzNjU4MzZjZTFlODQxZTYwYjZhZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SMOG2w9kPmWrSY-lfUAbgkK-OW1WoRsYouEnUvFusnE)

That will never work is it's not a vaild roll string (just try typing it in the chat box).  It's `/r dc` to roll combat dice, not `/r cd`.

Other than that, it all looks to be working as it should.  The new enrichment is purely for displaying the symbol when needed, and the CD variant is included to cover some of the ways the symbols appear when copy/pasteing from the core rulebook.
