### ISSUE TITLE
Actors should not take radiation damage from consumables if they are immune, and if not immune the amount of rads taken should be adjusted by an actor's base resistance.

### ISSUE THREAD

**Issue by teppuM** [Muttley/foundryvtt-fallout#267]
The super mutant in my party, marked immune to radiation, sometimes takes radiation damage when eating irradiated food. Can this be fixed?

For ghouls, it should still show when radiation damage _would_ have been taken. For Children of Atom, I think they are technically immune because of their innate radiation resistance of 1 and like ghouls, should be shown when they would've taken one.

**Comment by Muttley** [comment]
This is planned, but it will have to wait until I get time to enhance the active effects support.
