### ISSUE TITLE
Text for some item sheets seems to be broken

### ISSUE THREAD

**Issue by soltysek** [Muttley/foundryvtt-fallout#27]
As in description:
1. Weapon sheet `ITEM.TypeAmmo` probably should be some normal text like `Ammo Type`
![image](https://github.com/Muttley/foundryvtt-fallout/assets/1688660/f0605d02-858b-4ed1-9716-3ffd5e39b966)

2. Something also is wrong with selecting an item type. There is 'apparel' and 'apparel_mod' on the list and some translatable text should be present

Both issues were not present before.

**Comment by Muttley** [comment]
Are you using a specific translation, or just English?

**Comment by soltysek** [comment]
It is present on English and Polish, didn't check other ones.

**Comment by Muttley** [comment]
Ah, I see the issue.  Will have a fix out later this evening.

**Comment by soltysek** [comment]
That was quick ;) Thanks! ;)
