### ISSUE TITLE
Delayed Edit Item UI

### ISSUE THREAD

**Issue by BlubberNibble** [Muttley/foundryvtt-fallout#274]
Whenever I click to open an item's properties, it always takes two clicks in order for it go through, usually taking about 3 seconds before it even opens up. This delay happens even at a local level which shouldn't have any delay compared to online.

**Comment by Muttley** [comment]
What do you mean by opening an item's properties?  Clicking the Edit Item icon on a character sheet, or something else?

I can't replicate the behaviour you report.

**Comment by BlubberNibble** [comment]
> What do you mean by opening an item's properties? Clicking the Edit Item icon on a character sheet, or something else?
> 
> I can't replicate the behaviour you report.

Clicking on the edit button. I'm sorry I'm so bad at describing these things.

**Comment by Muttley** [comment]
Does this happen in a new world with no mods installed?

**Comment by BlubberNibble** [comment]
I just tested it now and it seems the problem doesn't occur. Sorry for bothering you, I'll go through the steps of seeing which module is causing it.
