### ISSUE TITLE
Add the ability to make an availability luck roll from the character sheet

### ISSUE THREAD

**Issue by sds2413** [Muttley/foundryvtt-fallout#275]
Make the "L" in special be a button that rolls dc equal to the number listed.

**Comment by Muttley** [comment]
Have you got a page reference for the game rule which calls for this?  I can't find one.

**Comment by sds2413** [comment]
Chapter 4 Equipment, obtaining equipment, availability and rarity, last paragraph. CRB pg 85. It dose not call it a luck roll, but that is how I have referred to it.
