### ISSUE TITLE
Display Fire Rate outside of Weapon Item

### ISSUE THREAD

**Issue by BlubberNibble** [Muttley/foundryvtt-fallout#283]
At it says in the tin, add the Fire Rate of a weapon into the inventory page and in the chat pop up when a character makes an attack. This should help reduce the amount of times the Weapon item needs to be opened.
![image](https://github.com/Muttley/foundryvtt-fallout/assets/115412663/13aa709d-dc3b-42f8-a79c-1cb930e56514)

**Comment by sds2413** [comment]
If possible also show the range of a weapon as well.
