### ISSUE TITLE
Life Giver Perk and HP totals

### ISSUE THREAD

**Issue by 123Jimbly** [Muttley/foundryvtt-fallout#295]
The Life Giver Perk increases the character's total HP by their END rank. With the current auto-calculation, the HP totals come out wrong. I much preferred being able to input my own HP total. Especially because Max HP is modified by Consumables and the Well-Rested state.

**Comment by Muttley** [comment]
If you look in the Documentation compendium, there's an Active Effects document which details the key you can use in an active effect to add bonuses if needed.
