### ISSUE TITLE
Derived Values to take into accounts other sources

### ISSUE THREAD

**Issue by frons79** [Muttley/foundryvtt-fallout#296]
For instance in the Player cs **MELEE DAMAGE** (but I guess it's true for the other values as well) does not take into accout the presence of Perks and Traits which can modify its dynamic output (i.e. Heavy Handed), but only the Strength score.
![Fallout_RPG_-_Pregenerated_Characters-pdf](https://github.com/Muttley/foundryvtt-fallout/assets/75011274/ecaa9e82-b320-4866-9dcc-beea4dfbc790)

**Comment by Muttley** [comment]
Perks are currently merely for reference when playing, later there may be automation added where it makes sense.

In the meantime you can adjust the melee damage bonus using Active Effects using the key detailed by the Active Effect document in the System Documentation compendium.
