### ISSUE TITLE
Spell Description Block No Pheonix Symbol

### ISSUE THREAD

**Issue by kaisch006** [Muttley/foundryvtt-fallout#298]
I love your addition of the Pheonix Dice symbols. Currently the description section of spell items is not updating with the Pheonix Dice symbol. This extends to everything within the spell item to include momentum spend descriptions and alternative effect descriptions.

**Comment by Muttley** [comment]
I think you may have the wrong system, the Phoenix symbol is from Conan, not Fallout.

**Comment by kaisch006** [comment]
I’m sorry I posted in the forum.
