### ISSUE TITLE
I can't put a value on the Active Effects related to Skills

### ISSUE THREAD

**Issue by pedroaugustobt** [Muttley/foundryvtt-fallout#318]
I want to put Athletics to modify, but I can't find the syntax that I need to put...
![image](https://github.com/Muttley/foundryvtt-fallout/assets/107325727/fc277262-8410-4040-a8dd-74b6f59b806f)

**Comment by Muttley** [comment]
Unfortunately, due to the fact that Actor skills are actually Items, it's not currently possible to use ActiveEffects to add bonuses

**Comment by pedroaugustobt** [comment]
> Unfortunately, due to the fact that Actor skills are actually Items, it's not currently possible to use ActiveEffects to add bonuses

Do you ever think about refactoring this specific part?

I ask why I can join the project if you don't mind

**Comment by Muttley** [comment]
> > Unfortunately, due to the fact that Actor skills are actually Items, it's not currently possible to use ActiveEffects to add bonuses
> 
> Do you ever think about refactoring this specific part?

Not the way skill items are handled specifically, but I do have plans for supporting various bonuses in other ways so they can be manipulated by Active Effects.

> I ask why I can join the project if you don't mind

Pull requests are always welcome, so if you want, feel free to pick a ticket from the "to-be-done" milestone ( https://github.com/Muttley/foundryvtt-fallout/milestone/2 ), or if you have a specific idea you'd like to do, create a ticket for it so we can discuss the best way to implement it.
