### ISSUE TITLE
Small Frame Recalculation

### ISSUE THREAD

**Issue by FeyFatale** [Muttley/foundryvtt-fallout#323]
As it currently stands, your carry weight is autocalculated, but Small Frame doesn't appear to override it, leaving the calculation as the normal version.

**Comment by Muttley** [comment]
Perks are currently merely for reference when playing, later there may be automation added where it makes sense.

In the meantime you can add a negative value to adjust the carray capacity on the Status tab of the character sheet:

![image](https://github.com/Muttley/foundryvtt-fallout/assets/853835/571f9dc3-69e7-4c6b-8d87-291d52fd3b4a)
