### ISSUE TITLE
NPC Carry Weight reverts

### ISSUE THREAD

**Issue by FeyFatale** [Muttley/foundryvtt-fallout#346]
Some NPCs, such as Mister Handy, have a carry weight that differs from the autocalculated carry weight. If you try to change the carry weight, it automatically resets when you do anything else, refusing to save the altered value.

**Comment by Muttley** [comment]
Those are misprints in the books, the calculation is correct.

**Comment by FeyFatale** [comment]
Even if that's the case, and I see no reason to believe that as they've never been errata'd (then again, neither have many of the other typos) and aren't even close in calculation (such as the super mutant suicider having 130 instead of 230), it also prevents making NPCs with things like Small Frame or that gain a disease that alter their carry weight.
