### ISSUE TITLE
How to add a custom source module

### ISSUE THREAD

**Issue by extazz17** [Muttley/foundryvtt-fallout#349]
Ref : #325 

Before the recent updates, I had created all the items, added custom compendium images.
I see that a filter is available to only fetch selected sources.

**How to add your own "custom" source?**
I don't understand what to do.

What do I mean, I would only have to put the "custom" source on all my compendium, otherwise I have all the items duplicated.

Thank you.

**Comment by Muttley** [comment]
Please see the example data module here: https://github.com/Muttley/foundryvtt-fallout-custom-module
