### ISSUE TITLE
Dice So Nice only show for the player who rolls

### ISSUE THREAD

**Issue by theMagius0** [Muttley/foundryvtt-fallout#397]
**Foundry Version**: 11.13 (Build 315)
**Fallout 2d20 Version**: 11.10.1
**Dice-So-Nice Version**: 4.6.10

If a player clicks a "roll" on their character sheet (e.g. Small Guns), then they see the Dice-So-Nice 3d animations.  However, no _other_ player at the (virtual) table can see the animated dice.  The same goes for the GM (only _they_ see the animations--not the players).

What's interesting about this bug is that:

1. The Dice-So-Nice animations were shown for _all_ players several Fallout 2d20 versions ago, and
2. If a gm/player rolls using the chat window (e.g. "/roll 1d6:"), then everyone at the (virtual) table _can_ see the animated dice.  

So, this _only_ seems to affect rolling directly from the character sheets.

Thx,

**Comment by BlubberNibble** [comment]
An addition I noticed is that when making attack roll with a weapon, the location die **does** roll properly and is visible for all players. In my game, using the built in macros for D20 and CDs does not display dice at all, it's not visible to anyone.
