### ISSUE TITLE
Show if books/magazines are learned on the character sheet.

### ISSUE THREAD

**Issue by QckSilverDragon** [Muttley/foundryvtt-fallout#400]
It would be convenient if there was some kind of icon or something showing if the currently equipped book had been learned. Currently you can only see this by editing the item.

**Comment by Muttley** [comment]
If it's been learned wouldn't you just add the talent and remove the magazine?

**Comment by QckSilverDragon** [comment]
I forgot they turned into perks once read.
I never created those perks.

Nevermind.
