### ISSUE TITLE
Rolling weapon attacks broken when using a non-English language setting

### ISSUE THREAD

**Issue by Teylah57** [Muttley/foundryvtt-fallout#428]
There is a bug when I use a gun it's use everytime the Strength and not apply the skill. Maybe it's because I don't use the English version?.

![2024-05-26 (1)](https://github.com/Muttley/foundryvtt-fallout/assets/148592880/e1196945-d1ff-4fde-b3a8-95b5e691930b)

**Comment by cnschu** [comment]
can you please describe exactly what buttons do you click, whatr behavior do you expect, and what happens instead?
"use a gun" can mean a lot :)

thanks.

**Comment by Teylah57** [comment]
ok so when I want to use for example a Pipe Gun, I click on the gun, the windows open and I see 4(attribut) + 0 for the skill and it should be 9+4. I notice that the bug use always the attribut Strength (and not Agility like for guns). This is the result: 
![2024-05-27](https://github.com/Muttley/foundryvtt-fallout/assets/148592880/9b07448a-c955-400f-93a1-10e53109e24b)
TN should be 13 and not 4.

**Comment by cnschu** [comment]
it seems that for the gun the skill is not set.
can you please show the details of the gun?

The detail screen should something like this:
<img width="458" alt="image" src="https://github.com/Muttley/foundryvtt-fallout/assets/32237924/3600aa09-a1fb-4495-83e1-c6f244b1f472">
