### ISSUE TITLE
Unable to alter max AP setting if you reduce it to zero

### ISSUE THREAD

**Issue by brunocalado** [Muttley/foundryvtt-fallout#436]
I set to 0 the AP bar and now I can't increase it...
https://github.com/Muttley/foundryvtt-fallout/assets/4999783/823bd7ad-4a03-467b-b3a4-23482d31d8a2

Tks

**Comment by Muttley** [comment]
Yep, that's a bug.  I'll fix it for the next release, but in the meantime you should be able to reset things back to normal by running the following command in either a script, or the console (hit F12 to open that):  `game.settings.set("fallout", "maxAP", 6)`
