### ISSUE TITLE
Settlements:  Current leader 

### ISSUE THREAD

**Issue by OvanLRU** [Muttley/foundryvtt-fallout#441]
The Current leader of a settlement needs to be able to pull from Characters list not just from the players. otherwise we cant set up NPC settlements correctly.

Temp Work Around: Create a player in the player list of foundry. Assign them a character (Settlement Leader) Then select Current Leader as the Settlement leader.

**Comment by Muttley** [comment]
Surely you can just use an NPC for this?

**Comment by OvanLRU** [comment]
I tried as you suggested but it will not give me the option to assign to settlement leader. Only the one that i made into a player works. 

![Screenshot 2024-06-19 144922](https://github.com/Muttley/foundryvtt-fallout/assets/141533095/c2995643-e4ab-477d-8879-39dafb01937c)

**Comment by Muttley** [comment]
You need to drag the NPC onto the settlement first so that they are a member of the settlement.

**Comment by OvanLRU** [comment]
> You need to drag the NPC onto the settlement first so that they are a member of the settlement.

Thank you Kind Sir. I have no idea why I thought it had to go the way I suggested.
