### ISSUE TITLE
Suggestion: Uncategorized Apparel Type

### ISSUE THREAD

**Issue by Havoclivekiller** [Muttley/foundryvtt-fallout#447]
I've upgraded Foundry to V11 (from V10), Fallout 2d20 made a change how armor was categorized, so it made all armor invisible on sheets (they were there, even counted), had to modify JSON files to get them back. My suggestion is that if the field "apparelType" is empty, it puts the items into a new Uncategorized table in the Apparel tab.

Also, this would allow groups to create armor types that aren't normal apparel - like some force fields or something else, that grant bonuses to the wearer.

**Comment by Muttley** [comment]
You can already do this kind of thing with Active Effects.

What I will do though is allow active effects to be added to Miscellany items if required: #491
