### ISSUE TITLE
FEATURE REQUEST: Referenceable Item value for other Foundry Crafting modules to use

### ISSUE THREAD

**Issue by SLENDERMAN95** [Muttley/foundryvtt-fallout#448]
For the common/uncommon/rare materials, it would be nice if they had an actual item tied to those values or some kind of attribute key that could be leveraged. 

Many of the other Foundry Crafting system add-ons require an actual item in your inventory to pull from for crafting. I think having these be some form of referenceable object would go a long way in compatibility. 

I do understand that I could just create the items myself, but you have spent a good amount of work on the junk tool and I would plan to keep using this system

If there is some referenceable value I could use, please let me know and close this out

**Comment by Muttley** [comment]
All these values are available on the character at the following keys:
```
system.materials.junk
system.materials.common
system.materials.uncommon
system.materials.rare
```
