### ISSUE TITLE
Ammo Item Types: Can not use custom made ammo in weapons

### ISSUE THREAD

**Issue by Schism989** [Muttley/foundryvtt-fallout#449]
I am unsure if this is user error, or if this is an issue with the system itself, but I'm unable to use custom-made ammunition types in weapons.

I came across this as I was trying to convert Wasteland Necessities into Foundry, and was trying to create the Ranger Sequoia and the .45-70 Gov't Ammo. While creating them was easy, it's apply .45-70 Gov't that I seem to be unable to do.

**Comment by Muttley** [comment]
You need to add new Ammo items into a compendium, then they will show up.  I've verified that this works as intended.
