### ISSUE TITLE
Cant Find HP Data Path and Max HP Data Path 

### ISSUE THREAD

**Issue by OvanLRU** [Muttley/foundryvtt-fallout#464]
Looking for the pathways that point towards the HP value of a actor. 
(standard DND5e: system.attributes.hp.value)
(Standard DND5e system.attributes.hp.max)
I am trying to map this to be able to run the Heartbeat Module.

**Comment by Muttley** [comment]
DnD5e system paths will not work as this isn't the DnD5e system.

You'll want `system.health.value` and `system.health.max`.

Handy hint: If you export a character from Foundry and open the file in a text edit you can see every value available.

**Comment by OvanLRU** [comment]
> DnD5e system paths will not work as this isn't the DnD5e system.
> 
> You'll want `system.health.value` and `system.health.max`.
> 
> Handy hint: If you export a character from Foundry and open the file in a text editor you can see every value available.

Yes sorry, I was just throwing it out as an example.  Thank you for the hint I did not know that was a thing.
