### ISSUE TITLE
Suggestion: Blind roll the D20 Roller and D6 Roller Macros

### ISSUE THREAD

**Issue by VroomVroom75** [Muttley/foundryvtt-fallout#465]
I don't show my players my dice results (for various reasons as a GM). Is there a way to have an option to blind roll the d20 and d6 macros?

**Comment by sito92** [comment]
Hello, just use built in options of Foundry before using macros:
<img width="292" alt="image" src="https://github.com/Muttley/foundryvtt-fallout/assets/8093045/6a187416-1a96-4bf0-a7e3-9693865f9ef5">

**Comment by Muttley** [comment]
Closing as this is already built in to Foundry as @sito92 pointed out.
