### ISSUE TITLE
Adding Items to character sheet doesn't show item visually

### ISSUE THREAD

**Issue by blackwolf602** [Muttley/foundryvtt-fallout#477]
Character sheet doesn't support usage of non fallout core items. Attempting to put items into the character sheet not from the Fallout: The Roleplaying Game will result in the item not visually appearing but will added into the inventory affecting weight.

**Comment by blackwolf602** [comment]
![image](https://github.com/Muttley/foundryvtt-fallout/assets/54816502/61586868-facd-4d07-8250-dbd4bb7c650b)
dragging the arm into the sheet adds the weight of the itme and says it's in the character but it doesn't visually reflect this unless the item is imported

**Comment by Muttley** [comment]
I'm unable to replicate this.  Are you using a mod to add the items?  If so, what happens when you just drag an item from the compendium manually?
