### ISSUE TITLE
Shouldn't clothing (not outfits) stack with armor?

### ISSUE THREAD

**Issue by MorganBard** [Muttley/foundryvtt-fallout#480]
Page 124 of the core rules states:

> Clothing provides little protection by itself but may 
> often provide small bonuses when combined with 
> armor worn over the top. Outfits generally grant more 
> protection or larger bonuses, at the cost of being una-
> ble to combine them with armor.

So if I have a character wearing Tough Clothing (1 physical and energy resistance, arms, torso, and legs) and wear raider armor on both arms (1 physical and energy resistance), I think I should have 2 physical and energy resistance on both arms, and 1 PR and ER on torso and legs. In Foundry, when I do this, I have only 1 for all locations. Am I missing something or is this a bug?

**Comment by Muttley** [comment]
No, the resistances don't stack as per the rules:

![image](https://github.com/user-attachments/assets/d235a575-e231-4783-a9f7-6e7903180077)

See page 122 of the core rulebook.
