### ISSUE TITLE
Robots as enemies/NPC

### ISSUE THREAD

**Issue by NurAnCZ** [Muttley/foundryvtt-fallout#516]
Would it be possible to adjust template for robot same way as for characters and creatures?

I am asking, because I am running Start set where Mr. Gutsy is enemy at one point.... I am trying to prepare his sheet, but I can't set it up as notable character, nor give him few more HP or some other changes that are in the book. (eg give him loot section) Also there is no calculation for XP given after defeating the robot.

Thank you for considering this

**Comment by Muttley** [comment]
I'm not sure what you're trying to do.  The Mr Gutsy should be set up as an NPC actor type, not a Robot actor type which are only for players.

**Comment by NurAnCZ** [comment]
Thank you, that explains everything, I totaly missed option to change it there.
