### ISSUE TITLE
Assistance calling the AGI attribute in the JS code (for Drag Ruler module)?

### ISSUE THREAD

**Issue by theMagius0** [Muttley/foundryvtt-fallout#517]
**Foundry**: 12 v331
**Fallout**: 11.13.0

Good afternoon.  I'm using your Fallout module with a Foundry module called "Drag Ruler".  

It used to work for me (several versions ago), but I think the class hierarchy has changed--in either Foundry, or your Fallout module, or both.  I'm a developer, but not so much with JS.  So, I was wondering if you could help me find out what to put in a data field so that "Drag Ruler" could access the AGI stat?

I have tried:

- actor.system.attributes.agi.value
- system.attributes.agi.value

But each of those seems to give different variants of the same error:

`Error: You are accessing TokenDocument#actorData which has been migrated to TokenDocument#delta
Deprecated since Version 11
Backwards-compatible support will be removed in Version 13`

And

`Error: You are accessing globalThis.mergeObject which must now be accessed via foundry.utils.mergeObject
Deprecated since Version 12
Backwards-compatible support will be removed in Version 14`

However, when I use the browser console to access this attribute using:

`game.actors.getName(<my character's name here>).system.attributes.agi.value`

It works just fine.

Can you help me to understand if there is _another_ way to call the AGI attribute?

Thx,

**Comment by Muttley** [comment]
There appears to be a calculated value avaialbe on actors named `system.unofficalSpeed`.  Yes, that's a spelling mistake, and no, I wasn't responsible for it.  ;)

If you still have issues, you'll need to get help from whoever develops the Drag Ruler module, as it's not one I use or am familiar with.
