### ISSUE TITLE
Missing Rate of fire for creatures and such

### ISSUE THREAD

**Issue by RAndomArmyStudios** [Muttley/foundryvtt-fallout#547]
![image](https://github.com/user-attachments/assets/7ab31434-cce3-46b3-979f-ba8fcc4f4708)
![image](https://github.com/user-attachments/assets/2ecd44f0-bf8a-4b78-9ecc-a582ab1b3384)

**Comment by QckSilverDragon** [comment]
Add ammo to the weapon. This will allow for adding a fire rate.
NPCs and creatures dont consume ammo on weapon use.
