### ISSUE TITLE
Use localized skill names to sort and display alphabetically on Character sheet

### ISSUE THREAD

**Issue by Sanawbicz** [Muttley/foundryvtt-fallout#60]
Is there any way to change the order of skills on the character sheet? I want the skills to be ordered differently (alphabetically, but in the Polish language).
Translation is good, but order is bad.

**Comment by Muttley** [comment]
Yeah, can definitely look into that.

**Comment by Muttley** [comment]
Pressed the wrong button.  :P

This look better?
![image](https://github.com/Muttley/foundryvtt-fallout/assets/853835/7d970d08-7ab4-40ad-9973-4b1af187becc)

**Comment by Sanawbicz** [comment]
Yes, looks good. Thank you :)
