### ISSUE TITLE
Play audio when item is used.

### ISSUE THREAD

**Issue by QckSilverDragon** [Muttley/foundryvtt-fallout#8]
It would be nice if a SFX audio file could be played when a weapon is shot or an item consumed.

**Comment by Muttley** [comment]
> It would be nice if a SFX audio file could be played when a weapon is shot or an item consumed.

Did the Automated Animations module end up providing this functionality for you?

**Comment by QckSilverDragon** [comment]
Yes it did. It would still be nice if the system had native support for this feature since AA in no longer in development. This is a snippet from their github.

"[NOTICE: Automated Animations is no longer being actively worked on, and should be considered to be in Maintenance Mode only.]"

**Comment by Muttley** [comment]
Having thought about this a great deal, I'm don't think implementing this within the system is the best way forward.  This should generally be handled by an system agnostic event based mod of some kind.

I might put it on my long list of potential projects to look at if I get the chance.
