### ISSUE TITLE
Non-Character weight calculations

### ISSUE THREAD

**Issue by teppuM** [Muttley/foundryvtt-fallout#81]
This might be a tall order but it would be massively appreciated if there could be automatic weight calculations for non-player characters. For example, a Brahmin is able to carry up to 500lbs, but the weight of what it is carrying isn't calculated automatically unless I make the brahmin a character. Another example is a Mutant Hound companion (Settlers guidebook pg67) can carry up to 50lbs of items, yet its inventory would need to be calculated by hand.

**Comment by Muttley** [comment]
We should be able to display the carried weight without too much problem.
