### ISSUE TITLE
AP tracker is missing

### ISSUE THREAD

**Issue by Kich43** [Muttley/foundryvtt-fallout#9]
Hi ! Ap tracker is missing for me. No module running btw.
![image](https://github.com/Muttley/foundryvtt-fallout/assets/98329830/07adde8a-3dbd-4f73-af1a-c2e147d7a6b2)

**Comment by Muttley** [comment]
Whoops.  Fixed.

**Comment by Kich43** [comment]
Thx ! Gj ^^
